#!/usr/bin/env node
/**
 * Generate docs/checks.md from the rules catalog (src/rules.js), so the docs cannot drift
 * from what the tool reports. test/output.test.js fails if the committed file is stale.
 * Usage: node scripts/build-docs.js
 */
import { writeFileSync } from 'node:fs';
import { RULES } from '../src/rules.js';

const GROUPS = [
  ['Package code and metadata (npm, PyPI)', ['undeclared-env', 'dynamic-env', 'install-script', 'network-egress', 'capability', 'instruction-like-text', 'typosquat', 'known-vulnerability', 'vuln-lookup-failed']],
  ['Where the code came from', ['provenance', 'provenance-dropped', 'publisher-mismatch', 'deprecated', 'archived-upstream']],
  ['The registry listing', ['listing-status', 'multiple-listings', 'no-package']],
  ['Hosted servers: sign-in', ['unauthenticated', 'custom-auth', 'oauth-metadata-missing', 'oauth-resource-mismatch', 'oauth-issuer-mismatch', 'oauth-no-pkce', 'oauth-dcr-only']],
  ['Hosted servers (probe and pins)', ['remote-not-probed', 'deprecated-transport', 'pinned', 'pins-updated', 'tool-description-changed', 'tool-schema-changed', 'tool-added', 'tool-removed', 'tools-truncated']],
  ['What your agents already trust (--installed)', ['plaintext-secret', 'credential-unresolved', 'unpinned-launch', 'not-scanned', 'scan-error']],
  ['Semantic judgment (optional)', ['undisclosed-capability', 'disclosure-unclear', 'disclosure-not-judged']],
];

export function renderChecksDoc() {
  const listed = new Set(GROUPS.flatMap(([, ids]) => ids));
  const missing = Object.keys(RULES).filter((id) => !listed.has(id));
  if (missing.length) throw new Error(`checks not placed in a group: ${missing.join(', ')}`);
  const out = [
    '# What mcpscan checks',
    '',
    '<!-- Generated by scripts/build-docs.js from src/rules.js. Edit the catalog, not this file. -->',
    '',
    'Every finding names one of these checks. The same list is in the tool: `mcpscan explain`, or',
    '`mcpscan explain <check>` for one. Severity is per finding; the level shown is the usual one',
    '(a credential read is high, an ordinary setting is low, under the same check).',
    '',
    'Severity, in plain terms: **high**, do not install until you have looked. **medium**, worth',
    'understanding before you rely on it. **low**, good to know. **info**, context, not a problem',
    '(a filesystem server writing files is the product working).',
    '',
  ];
  for (const [title, ids] of GROUPS) {
    out.push(`## ${title}`, '');
    for (const id of ids) {
      const r = RULES[id];
      out.push(`### \`${id}\`: ${r.title}`, '', `Usual severity: **${r.level}**`, '', `**Why it matters.** ${r.why}`, '', `**What to do.** ${r.fix}`, '');
    }
  }
  return `${out.join('\n').trimEnd()}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(new URL('../docs/checks.md', import.meta.url), renderChecksDoc());
  console.log('wrote docs/checks.md');
}
